#!/bin/zsh

output=${1}

# tag: v3.21.12
cmake ../ \
-DCMAKE_INSTALL_PREFIX=${output} \
-DCMAKE_BUILD_TYPE=release \
-DCMAKE_APPLE_SILICON_PROCESSOR=arm64 \
-Dprotobuf_FORCE_FETCH_DEPENDENCIES=ON \
-DCMAKE_SYSTEM_PROCESSOR=arm64 \
-DCMAKE_CXX_STANDARD=17 \
-DCMAKE_CXX_STANDARD_REQUIRED=ON \
-DCMAKE_CXX_EXTENSIONS=OFF \
-Dprotobuf_BUILD_TESTS=OFF
